version: '3.9'
services:
  express-app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - express-app-mongodb:/data/db

volumes:
  express-app-mongodb:
