version: '3.9'
services:
  express-app:
    build:
      args:
        - NODE_ENV=development
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_IP=${MONGO_IP}
      - MONGO_PORT=${MONGO_PORT}
    volumes:
      - .:/home/node/express-app:ro
      - /home/node/express-app/node_modules
    command: npm run dev
